# Generated by Django 3.2.5 on 2021-07-29 19:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('title', models.TextField()),
                ('image', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
            ],
            options={
                'db_table': 'main_About',
            },
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'main_banner',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('metaTitle', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'main_category',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('fullname', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'main_contact',
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('product_id', models.TextField()),
                ('imageThumb', models.TextField()),
                ('imageSmall', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'main_image',
            },
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('order_id', models.TextField()),
                ('product_id', models.TextField()),
                ('total_price', models.TextField()),
                ('product_amount', models.TextField()),
            ],
            options={
                'db_table': 'main_order_detail',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('user_id', models.TextField()),
                ('fullname', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('note', models.TextField()),
                ('create_on', models.TextField()),
                ('shipping_status', models.TextField()),
                ('bill_address', models.TextField()),
            ],
            options={
                'db_table': 'main_orders',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('category_id', models.TextField()),
                ('supplier_id', models.TextField()),
                ('name', models.TextField()),
                ('quantity', models.TextField()),
                ('link', models.TextField()),
                ('image', models.TextField()),
                ('price', models.TextField()),
                ('productCode', models.TextField()),
                ('featureData', models.TextField()),
            ],
            options={
                'db_table': 'main_product',
            },
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('company_name', models.TextField()),
                ('image', models.TextField()),
                ('weburl', models.TextField()),
                ('telephone', models.TextField()),
                ('email', models.TextField()),
                ('country', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'main_provider',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('fullname', models.TextField()),
                ('birthday', models.TextField()),
                ('gender', models.TextField()),
                ('phonenumber', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('role_id', models.TextField()),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('instagram', models.TextField()),
            ],
            options={
                'db_table': 'main_users',
            },
        ),
    ]
