# Generated by Django 3.2.4 on 2021-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('image', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('metaTitle', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('imageThumb', models.TextField()),
                ('imageSmall', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('product_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('fullname', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('note', models.TextField()),
                ('create_on', models.TextField()),
                ('shipping_status', models.TextField()),
                ('bill_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('name', models.TextField()),
                ('quantity', models.TextField()),
                ('link', models.TextField()),
                ('image', models.TextField()),
                ('price', models.TextField()),
                ('productCode', models.TextField()),
                ('featureData', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('image', models.TextField()),
                ('weburl', models.TextField()),
                ('telephone', models.TextField()),
                ('email', models.TextField()),
                ('country', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('fullname', models.TextField()),
                ('birthday', models.TextField()),
                ('gender', models.TextField()),
                ('phonenumber', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('role_id', models.IntegerField()),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('gmail', models.TextField()),
                ('instagram', models.TextField()),
            ],
        ),
    ]
